### PR TITLE
add libdir patch

### PR DESCRIPTION
**Pull request by martinkg**
add libdir patch for multilib support.
https://github.com/hluk/qxtglobalshortcut/issues/3

### CODE REVIEW

**Review by hluk — CHANGES_REQUESTED** [review]
Looks like it breaks builds on Travis CI.

```
CMake Error at cmake/library.cmake:37 (install):
install TARGETS given no LIBRARY DESTINATION for shared library target
"qxtglobalshortcut".
Call Stack (most recent call first):
CMakeLists.txt:27 (include)
```

**Review by martinkg — COMMENTED** [review]
add libdir patch correction

**Comment by martinkg** [comment]
add libdir patch correction

**Comment by hluk** [comment]
Nice, thanks for the patch!

**Pull request merged**
